### ISSUE TITLE
make clean will remove all cpp files

### ISSUE THREAD

**Issue by huwan** [kaifishr/CppMultilayerPerceptron#1]
Running `make clean` will remove all .cpp files. 
https://github.com/KaiFabi/CppMultilayerPerceptron/blob/9a96fb6c1a45b5369e1503b4b15235404fa43005/src/makefile#L5
Replacing `.c` in the above line by `.cpp` will fix this issue.

**Comment by kaifishr** [comment]
@huwan has been fixed by @davide-giacomini :)
